animal = "  chanchito feliz  "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.find("fe"))
print(animal.find("CH"))
print(animal.replace("nch", "j"))
print("nch" in animal)
print("ncH" not in animal)